'''
"Hello" ** 5

format - .format	
f

addition of 100 and 10 is 110

palceholder  - {}

assignment - value assign 
a=5
a=100
number1=90

-->number1=90+10

--> number1=number1+10

--> number1+=10

Lab task - %= , //= , **/

--> comparison operator 

>
<
>=
<=
==
!=


logical 

and or not 


4th Sep
Operators - 
		Arithmatic - +,-,/,*,//,**,%
		Assignment  +=,*=,-....
		comparison  ==,>=,<=,!=
		Logical and or not (compound)	

		num=120 num2=60
		num>100 and num>num2 - both condition must be true 
		120>100 and 120>60  - True
	
		num=50 num2 10
		50>100 and 50>10 - False	

		num>100 or num>num2 - either of condition is true it return tru
		120>100 or 120>60  - True

		num=50 num2 10
		50>100 or 50>10 - True

		membership operator
			in not it

		identity is nested list 
		lst1 = [1,2,3,[2,3,4]]		
		lst2 [2,3,4]
		
		 list with list type / value
			== value
'''
