#1.UPPER CASE 2.LOWER CASE 3.TITLE 4.CAPITALIZATION
name = "Tops Technologies pvt ltd"
word = name.upper()
print(word)#All Letter Capital

name = "Tops Technologies pvt ltd"
word = name.lower()
print(word)#All Latter Small 

name = "Tops Technologies pvt ltd"
word = name.title()
print(word)#All First Latter Capitalize

name = "Tops Technologies pvt ltd"
word = name.capitalize()
print(word) #only First Letter Capitalize
