#1.isdigit 2.isalpha 3.isalnum
str1 = "Tops"
str2 = "1234"
str3 = "Tops@123"
str4 = "Tops Tech"

print(f"str1.isdigit(){str1.isdigit()},str1.isalpha(){str1.isalpha()},str1.isalnum(){str1.isalnum()}")
print(f"str2.isdigit(){str2.isdigit()},str2.isalpha(){str2.isalpha()},str2.isalnum(){str2.isalnum()}")
print(f"str3.isdigit(){str3.isdigit()},str3.isalpha(){str3.isalpha()},str3.isalnum(){str3.isalnum()}")
