#1.ARITHMETIC OPERATOR
'''
| Operator | Name                            | Example   | Output     |
| -------- | ------------------------------- | --------- | ---------- |
| `+`      | Addition                        | `10 + 5`  | `15`       |
| `-`      | Subtraction                     | `10 - 5`  | `5`        |
| `*`      | Multiplication                  | `10 * 5`  | `50`       |
| `/`      | Division (float result)         | `10 / 3`  | `3.333...` |
| `//`     | Floor Division (integer result) | `10 // 3` | `3`        |
| `%`      | Modulus (remainder)             | `10 % 3`  | `1`        |
| `**`     | Exponentiation (power)          | `2 ** 3`  | `8`        |

'''
a = 10
b = 3
c = 4
print("Addition:", a + b)        # 13
print("Subtraction:", a - b)     # 7
print("Multiplication:", a * b)  # 30
print("Division:", a / b)        # 3.333...
print("Floor Division:", a // b) # 3
print("Modulus:", a % b)         # 1
print("Power:", a ** b)          # 1000

print("power:",a ** c)           # 10000
